
settings = open ('settings.json','w') 
settings.write('['+'\n')
settings.write('  {\n')
settings.write('    "type": "numeric",\n')
settings.write('    "title": "Up hours",\n')
settings.write('    "desc": "Choose the time up ",\n')
settings.write('    "section": "time_up",\n')
settings.write('    "key": "time_hour"\n')
settings.write('  },')
settings.write('  {\n')
settings.write('    "type": "numeric",\n')
settings.write('    "title": "Up min",\n')
settings.write('    "desc": "Choose the time up",\n')
settings.write('    "section": "time_up",\n')
settings.write('    "key": "time_min"\n')
settings.write('  },')
settings.write('  {\n')
settings.write('    "type": "numeric",\n')
settings.write('    "title": "Down hours",\n')
settings.write('    "desc": "Choose the time down",\n')
settings.write('    "section": "time_down",\n')
settings.write('    "key": "time_hour"\n')
settings.write('  },')
settings.write('  {\n')
settings.write('    "type": "numeric",\n')
settings.write('    "title": "Down min",\n')
settings.write('    "desc": "Choose the time down",\n')
settings.write('    "section": "time_down",\n')
settings.write('    "key": "time_min"\n')
settings.write('  },')

for i in range(1,118):
    settings.write('  {\n')
    settings.write('    "type": "string",\n')
    settings.write('    "title": "Frame'+str(i)+'",\n')
    settings.write('    "desc": "Choose name '+str(i)+'",\n')
    settings.write('    "section": "Frame'+str(i)+'",\n')
    settings.write('    "key": "name"\n')
    settings.write('  },')
    settings.write('  {\n')
    settings.write('    "type": "numeric",\n')
    settings.write('    "title": "Time in sec '+str(i)+'",\n')
    settings.write('    "desc": "Choose the time '+str(i)+'",\n')
    settings.write('    "section": "Frame'+str(i)+'",\n')
    settings.write('    "key": "time_sec"\n')
    settings.write('  },')
    if i!=117:
        settings.write('  {\n')
        settings.write('    "type": "bool",\n')
        settings.write('    "title": "LED on transition'+str(i)+'",\n')
        settings.write('    "desc": "led transition enable '+str(i)+'",\n')
        settings.write('    "section": "Frame'+str(i)+'",\n')
        settings.write('    "key": "led"\n')
        settings.write('  },')
        
settings.write(']'+'\n')
settings.close()

